### ISSUE TITLE
Second run of "npm install" leads to errors

### ISSUE THREAD

**Issue by koppor** [cujojs/seed#1]
I'm checking out the master branch and follow the quickstart tutorial.

During npm install, I got following warning:
npm WARN prefer global bower@0.7.0 should be installed with -g

After a second run of npm install, I get following errors:

There were errors, here's a summary of them:
- cola Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\cola manually.
- curl Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\curl manually.
- meld Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\meld manually.
- poly Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\poly manually.
- when Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\when manually.
- wire Local path is a local repository
  To avoid losing work, please remove C:\git-repositories\linda\linda-frontend\lib\wire manually.

Am I disallowed to run "npm install" twice? What is the correct sequence of commands if a new dependency is added to  component.json?

**Comment by briancavalier** [comment]
My guess is that there is something going badly with npm or bower on windows.  I know there have been problems reported on both tools in windows, but I don't have a windows system to test with right now.

On OS X, I'm able to run npm install > 1 time on a fresh clone without any problems.

As a test, could you try installing bower globally (`npm install -g bower`), and then running `bower install` in the same quickstart clone where you are seeing these problems?  Let us know what happens--hopefully it will help narrow the problem down a bit.

**Comment by koppor** [comment]
That works perfectly.

**Comment by briancavalier** [comment]
Ok, if that works then my current theory is that there is something strange about using a local (non -g) install of bower in windows. It's not clear to me beyond that, though.  It almost sounds like bower installed the cujo components, but somehow thinks each one is a git repository and is refusing to overwrite or update it on subsequent runs.

Here is a test you could try:
1. Remove your global bower: npm rm -g bower
2. Get a fresh clone of the quickstart repo, and run npm install _once_
3. Look in lib/when to see if there is a .git directory. There should _not_ be one, but if there is, that may be the problem.

I'll also see if I can set up a test in a windows environment to try to reproduce. Thanks for helping to work through this!

**Comment by koppor** [comment]
Now it works, even a second install. Don't know, what went wrong. As far as I remember, at the last try, there have been `.git` directories lying around.

**Comment by briancavalier** [comment]
Very strange! If it happens again, please do reopen this issue and let us ok now if you find more clues. Thanks for your patience and willingness to work through these windows issues!
