### ISSUE TITLE
Use data-curl-run attribute

### ISSUE THREAD

**Issue by koppor** [cujojs/seed#3]
The new loading style of applications seems to be `<script data-curl-run="app/run" src="lib/curl/src/curl.js"></script>`. This should replace the current loader in index.html.

**Comment by briancavalier** [comment]
AFAIK, this feature isn't released in curl yet, but pinging @unscriptable to verify.  If it's not, then we will make this change after it is released.

**Comment by unscriptable** [comment]
Good catch @koppor. This feature is still in dev as @briancavalier notes.  Thanks for opening it as a reminder.  -- John

**Comment by unscriptable** [comment]
I have a [branch (cram)](https://github.com/cujojs/seed/tree/cram) implementing this feature.  It's not quite working.  For some reason (a bug in curl.js?), the app is being loaded twice: app/run.cram.js (crammed app) is loaded and then app/run.js (un-crammed app) is loaded.

**Comment by unscriptable** [comment]
This is in dev now!
