### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by moravcik** [cujojs/seed#6]
I have followed all the steps to install and start the seed project, but I couldn't get it working in the browser, saying: `Uncaught ReferenceError: curl is not defined` 

![screenshot at 2013-05-19 12 09 12](https://f.cloud.github.com/assets/1102311/522802/2d737128-c06c-11e2-976e-ae96fb74bcb8.png)

![screenshot at 2013-05-19 12 10 55](https://f.cloud.github.com/assets/1102311/522804/6ee1d44c-c06c-11e2-8314-3b3af212f323.png)

curl is listed as first dependency in `component.json` so there might be a problem with all of them

I see no 'lib' directory the the app folder itself and during the `npm install` I got some bower warnings:

```
bower warn Using deprecated "component.json". Please use "bower.json" instead
```

My system is Ubuntu 12.04 LTS 64bit

**Comment by unscriptable** [comment]
Hmmm, looks like bower 0.9 is silently failing. We're on it.

Thanks @moravcik!

**Comment by unscriptable** [comment]
Yep. bower 0.9 has some issues with dependencies that have blank strings.  We added explicit version numbers and tested.  Closing this.  Please reopen this if you are still experiencing problems after updating.  -- John

**Comment by moravcik** [comment]
Thank you. It works now, I can dig in ;)

Michal

2013/5/20 John Hann notifications@github.com

**Comment by briancavalier** [comment]
@moravcik Cool, thanks for letting us know about this!  Hope you enjoy :)  Feel free to join us on IRC freenode in #cujojs if you have questions or want to see what other folks are doing with cujoJS.
