### ISSUE TITLE
Add note about volo compatibility

### ISSUE THREAD

**Issue by briancavalier** [cujojs/seed#7]
As [pointed out](https://twitter.com/BlaineBublitz/status/341344954959949825) by @phated, seed works great with `volo create`, e.g. `volo create my-awsum-cujojs-project cujojs/seed`.  We should add instructions in the README.

**Comment by unscriptable** [comment]
If this is really a no-brainer, then I have no objections. :)

**Comment by briancavalier** [comment]
Yeah, it works on master as is, no code or package.json changes required, so seems pretty low maintenance for us.  I'll whip up a quick pull request.
